#!/usr/bin/env sh
# Generate a Homebrew formula for the macOS arm64 standalone binary.

set -eu

dist_dir="${1:-dist}"
tag="${2:-${GITHUB_REF_NAME:-}}"
asset="dw-macos-aarch64"
formula="$dist_dir/dw.rb"

err() {
    printf 'error: %s\n' "$*" >&2
    exit 1
}

[ -n "$tag" ] || err "release tag is required"
[ -s "$dist_dir/$asset" ] || err "missing release asset: $dist_dir/$asset"

if command -v sha256sum >/dev/null 2>&1; then
    sha256=$(sha256sum "$dist_dir/$asset" | awk '{print $1}')
elif command -v shasum >/dev/null 2>&1; then
    sha256=$(shasum -a 256 "$dist_dir/$asset" | awk '{print $1}')
else
    err "sha256sum or shasum is required"
fi

version="${tag#v}"

cat > "$formula" <<EOF
# Generated by durable-workflow/cli release workflow.
class Dw < Formula
  desc "Command-line interface for Durable Workflow Server"
  homepage "https://durable-workflow.com"
  url "https://github.com/durable-workflow/cli/releases/download/${tag}/${asset}"
  sha256 "${sha256}"
  version "${version}"

  def install
    bin.install "${asset}" => "dw"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dw --version")
  end
end
EOF
